version: 2
updates:
- package-ecosystem: cargo
  directory: "/vendor/"
  schedule:
    interval: weekly
    time: "08:00"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
